food(pizza).
food(rise).
bird(parrot).
island(srilanka).
animal(dog).
fuit(kiwi).
weapon(gun).
hardware(keyboard).
androidPhone(samsung).
male(kamal).
student(john).
black(element).
shape(circle).
vehicle(bus).
food(mango).

likes(john,ann).
studies(charlie,ai).
teaches(collins,cs).
loves(vincent,mia).
next_month(october,september).
is_a_student_of(jane,roy).
color_of(elephant,black).

month(january).
month(february).
month(march).
month(april).
month(may).
month(june).
month(july).
month(august).
month(september).
month(october).
month(november).
month(december).
